// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mC_Connect_table.Data;

#nullable disable

namespace mC_Connect_table.Migrations
{
    [DbContext(typeof(OrderViewContext))]
    [Migration("20250114015910_MakeOrderNumberDBGenerated")]
    partial class MakeOrderNumberDBGenerated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("mC_Connect_table.Models.OrderViewModel", b =>
                {
                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("DessertItems")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("DrinkItems")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("EntreeItems")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TableNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderNumber");

                    b.ToTable("OrderViewModel");
                });
#pragma warning restore 612, 618
        }
    }
}
