// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mC_Connect_table.Data;

#nullable disable

namespace mC_Connect_table.Migrations.RestaurantTables
{
    [DbContext(typeof(RestaurantTablesContext))]
    [Migration("20250123173918_AddSessionIDandCustomername")]
    partial class AddSessionIDandCustomername
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("mC_Connect_table.Models.RestaurantTables", b =>
                {
                    b.Property<int>("TableNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MctId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TableNumber");

                    b.ToTable("RestaurantTables");
                });
#pragma warning restore 612, 618
        }
    }
}
